spring.application.name=AI-Resume-Analyzer

server.port=8080

spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=resumeiq

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.ai.openai.api-key=YOUR_API_KEY
spring.ai.openai.chat.options.model=gpt-4o-mini

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB