spring.application.name=AI-Resume-Analyzer

server.port=8080

spring.data.mongodb.uri=mongodb+srv://sarthakgupta2303_db_user:Sarthak2025@finestay.i1f1d14.mongodb.net/?appName=finestay
spring.data.mongodb.database=resumeiq

jwt.secret=1234567890abcdefghih1234567890ab
jwt.expiration=86400000

gemini.api.key=${GEMINI_API_KEY}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB