spring.application.name=AI-Resume-Analyzer

server.port=8080

spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=resumeiq

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
openai.api.key=YOUR_OPENAI_API_KEY
openai.model=gemini-1.5-flash-latest

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB